version: '3'
services:
  # front:
  #   build: ./modules/module_Front
  #   ports:
  #    - "80:80"
  authentication:
    build: ./modules/module_Authentication
    ports:
     - "5002:5002"
  authorization:
    build: ./modules/module_Authorization
    ports:
     - "5003:5003"
  parser:
    build: ./modules/module_API-IMDB
    ports:
     - "5013:5013"
  comment:
    build: ./modules/module_Comment
    ports:
     - "5005:5005"
  movie:
    build: ./modules/module_Movie
    ports:
     - "5011:5011"
  search:
    build: ./modules/module_Search
    ports:
     - "5012:5012"