version: '3'
services:
  authentication:
    build: ./modules/Authentication
    container_name: authentication
    ports:
     - "5002:5002"
  authorization:
    build: ./modules/Authorization
    container_name: authorization
    ports:
     - "5003:5003"
  parser:
    build: ./modules/API-IMDB
    container_name: parser
    ports:
     - "5013:5013"
  comment:
    build: ./modules/Comment
    container_name: comment
    ports:
     - "5005:5005"
  movie:
    build: ./modules/Movie
    container_name: movie
    ports:
     - "5011:5011"
  search:
    build: ./modules/Search
    container_name: search
    ports:
     - "5012:5012"
  front:
    build: ./modules/Front
    container_name: front
    ports:
     - "8080:8080"